import bcrypt from 'bcrypt';

const BCRYPT_COST_FACTOR = 12;

/**
 * Hashes a plaintext password using bcrypt with cost factor 12.
 * A secure random salt is automatically generated by bcrypt.
 */
export async function hashPassword(plaintext: string): Promise<string> {
  return bcrypt.hash(plaintext, BCRYPT_COST_FACTOR);
}

/**
 * Verifies a plaintext password against a stored bcrypt hash.
 * Comparison is performed in constant time by the bcrypt library.
 */
export async function comparePassword(plaintext: string, hash: string): Promise<boolean> {
  return bcrypt.compare(plaintext, hash);
}